import Link from "next/link";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div>
            <p>Projects</p>
            {children}
        </div>
    );
}
